---
- include_tasks: setup.yml
  when: monit_setup_mode

- name: Copy monit config files
  template:
    src: "templates/etc/monit/conf.d/{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}"
    mode: 0644
  with_items: "{{ monit_scripts }}"
  notify:
    - restart monit
  when: monit_setup_mode

- name: Copy monit template config files
  template:
    src: "templates/etc/monit/conf.d/{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}-{{ service_name }}"
    mode: 0644
  with_items: "{{ monit_template_scripts }}"
  notify:
    - restart monit
  when: monit_setup_mode
