---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Empty monit config files directory
  file:
    path: /etc/monit/conf.d/*
    state: absent
  ignore_errors: yes

- name: Copy monit config files
  template:
    src: "templates/etc/monit/conf.d/{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}"
    mode: 0644
  with_items: "{{ monit_scripts }}"

- name: Copy monit template config files
  template:
    src: "templates/etc/monit/conf.d/{{ item }}"
    dest: "/etc/monit/conf.d/{{ item }}-{{ service_name }}"
    mode: 0644
  with_items: "{{ monit_template_scripts }}"

- name: Copy monit slack script
  template:
    src: "templates/etc/monit/slack_notifications.sh"
    dest: "/etc/monit/slack_notifications.sh"
    mode: 0744

- name: Restart monit
  service:
    name: monit
    state: restarted
    enabled: yes
