---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Copy monitrc configuration file
  template:
    src: "templates/etc/monit/monitrc.j2"
    dest: "/etc/monit/monitrc"
    mode: 0600
  notify:
    - restart monit

- name: Delete monit config files directory
  file:
    path: /etc/monit/conf.d
    state: absent
  ignore_errors: yes
  notify:
    - restart monit

- name: Create monit config files directory
  file:
    path: /etc/monit/conf.d
    state: directory
    mode: 0755
    owner: root
    group: root
  notify:
    - restart monit

- name: Copy monit slack script
  template:
    src: "templates/etc/monit/slack_notifications.sh"
    dest: "/etc/monit/slack_notifications.sh"
    mode: 0744
  notify:
    - restart monit

- name: Enable the Monit service
  service:
    name: monit
    enabled: yes
