---
- name: Install monit
  apt:
    pkg: "{{ item.package }}={{ item.version }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - { package: monit, version: "{{ monit_version }}"}
  notify:
    - restart monit
